week_06/day_01/code/BookApp/config/routes.rb
Rails.application.routes.draw do
  resources :authors, :books
  # Create a full set of RESTful URLs for the authors table (e.g. /authors, /authors/:id)

  resources :genres, only: [:index, :show]
  # Create CRUD urls for Genres, just for index and show
end

week_06/day_01/code/BookApp/app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id          :integer          not null, primary key
#  name        :string
#  dob         :date
#  location    :string
#  image       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Author < ApplicationRecord
  has_many :books
  # This defines a method called books on every instance of Author
  # When you call this method, it will get all associated books (based on author_id)

  has_many :genres, through: :books
  # ActiveRecord knows that we can call .books
  #   It also knows that every book in that collection, has genres
  #   For every book, call .genres and then give back to me (as an array)
end

week_06/day_01/code/BookApp/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string
#  blurb      :string
#  image      :string
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ApplicationRecord
  belongs_to :author
  # For every instance of Book, if you call .author - go and find the associated Author
  # BOOK MUST HAVE author_id

  has_and_belongs_to_many :genres
  # This relies on:
  #  A table called books_genres
  #  That table has book_id and genre_id
  # It allows us to call .genres on any book

  # When you call .genres on a particular book, go through the join table books_genres and find all related genres
end

week_06/day_01/code/BookApp/app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id   :integer          not null, primary key
#  name :string
#

class Genre < ApplicationRecord
  has_and_belongs_to_many :books
  # If you call .books, go through books_genres and find all related books
end

week_06/day_01/code/BookApp/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
    # Instance variables can be used in the view
  end

  def show
    # params[:id] is the dynamic part of the URL
    @author = Author.find_by(id: params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.create(author_params)
    redirect_to authors_path # -> Index method
    # redirect_to author_path(author) # -> Show method
  end

  # 1. Add a link to edit on the show page of every author (using link_to - find the page using /rails/info/routes)
  # 2. Render the partial on the edit page
  # 3. ...

  def edit
    @author = Author.find_by(id: params[:id])
  end

  def update
    author = Author.find_by(id: params[:id])
    author.update(author_params)
    redirect_to author_path(author) # -> Show method
    # redirect_to authors_path # -> Index method
  end

  # DELETE /authors/:id
  def destroy
    author = Author.find_by(id: params[:id])
    author.destroy
    redirect_to authors_path # Make a new get request to /authors
  end

  private

  def author_params
    params.require(:author).permit(:name, :location, :dob, :image, :description)
  end
end

week_06/day_01/code/BookApp/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  def index
    @books = Book.all
    # Create a ul filled with all book titles in index.html.erb (using an each loop)
  end

  def show
    @book = Book.find_by(id: params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    # details = {
    #   title: params[:book][:title],
    #   image: params[:book][:image],
    #   blurb: params[:book][:blurb],
    #   author_id: params[:book][:author_id],
    #   genre_ids: params[:book][:genre_ids],
    # }
    # book = Book.create(details)
    book = Book.create book_params
    redirect_to book_path(book)
  end

  def edit
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :blurb, :author_id, genre_ids: [])
  end
end

week_06/day_01/code/BookApp/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
    # Go to the view, create a list of all genres
  end

  def show
    @genre = Genre.find_by(id: params[:id])
  end
end

week_06/day_01/code/BookApp/app/helpers/authors_helper.rb
module AuthorsHelper
end

week_06/day_01/code/BookApp/app/helpers/books_helper.rb
module BooksHelper
end

week_06/day_01/code/BookApp/app/helpers/comments_helper.rb
module CommentsHelper
end

week_06/day_01/code/BookApp/app/helpers/genres_helper.rb
module GenresHelper
end

week_06/day_01/code/BookApp/app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <div>
    <%= f.label :title, "What is the title?" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :image, "Where is the image?" %>
    <%= f.url_field :image %>
  </div>
  <div>
    <%= f.label :blurb, "Describe the book" %>
    <%= f.text_area :blurb %>
  </div>
  <div>
    <%= f.label :author_id, "Who wrote this book?" %>
    <%= f.collection_select :author_id, Author.all, :id, :name %>
    <!--
      :author_id === what this piece of data should be called in params
      Author.all === the collection to show (the options for the user)
      :id        === when you select something, the ID is added to params
      :name      === the text in each option (the things that you select)
    -->
  </div>
  <div>
    <%= f.label :genre_ids, "What genre is this book?" %><br>
    <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name %>
    <!--
      :genre_ids is the key in params
      Genre.all is the collection that we are showing
      :id is the value that will be added into params
      :name is the text to show to the user
    -->
  </div>

  <%= f.submit %>
<% end %>

week_06/day_01/code/BookApp/app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

week_06/day_01/code/BookApp/app/views/books/index.html.erb
<h2>All Books</h2>

<% @books.each do |book| %>
  <div class="book">
    <h3>
      <%= book.title %>
    </h3>
    <%= link_to "See more", book_path(book) %>
  </div>
<% end %>

week_06/day_01/code/BookApp/app/views/books/new.html.erb
<h2>Add a new book</h2>

<%= render partial: "form" %>

week_06/day_01/code/BookApp/app/views/books/show.html.erb
<h2>
  <%= @book.title %>
</h2>

<p>
  <%= @book.blurb %>
</p>

<p>
  Written by: 
  <%= link_to @book.author.name, author_path(@book.author) %>
</p>

<h4>All Genres</h4>

<% @book.genres.each do |genre| %>
  <p>
    <%= link_to genre.name, genre_path(genre) %>
  </p>
<% end %>